language: rust
# cache: cargo
dist: trusty
sudo: true
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
      - zlib1g-dev

# Run builds for all the supported trains
rust:
  - nightly
  - beta
  - stable
  - 1.20.0

before_script:
  - export PATH=$PATH:~/.cargo/bin
  - ./travis-helper.sh install_deps

script:
  - cargo build --verbose
  - cargo package --verbose
  - cargo test --verbose
  - cargo build --verbose --features beta
  - cargo test --verbose --features beta
  - cargo build --verbose --features unstable
  - cargo test --verbose --features unstable
  - ./travis-helper.sh clippy_run
  # Won't work since our binary name is different from the crate name.
  # - ./travis-helper.sh dep_run
  - ./travis-helper.sh fmt_run

after_success:
  - ./travis-helper.sh upload_code_coverage
  - ./travis-helper.sh upload_documentation

notifications:
  email:
    recipients:
      - razican@protonmail.ch
      - brunoop@protonmail.ch
      - sergiodlo@protonmail.com
      - jaimesr@protonmail.ch
    on_success: change
    on_failure: always
